### ISSUE TITLE
如果的文件中有非视频、字幕文件时会无法正确导入

### ISSUE THREAD

**Issue by album-GitHub** [nuthx/subtitle-renamer#13]
如题，因为平时整理时文件夹里有nfo文件保存着刮削的信息，每次都手动选择视频比较难受。。。。。

**Comment by album-GitHub** [comment]
也希望出一个选项可以复制字幕而不是原地改名or剪切字幕

**Comment by nuthx** [comment]
能否给截图看一下，是包含了nfo文件吗？如果没在设置中填写nfo格式，默认只会包含字幕和视频格式的。

复制字幕功能下版本会加入。

**Comment by album-GitHub** [comment]
> 能否给截图看一下，是包含了nfo文件吗？如果没在设置中填写nfo格式，默认只会包含字幕和视频格式的。
> 
> 复制字幕功能下版本会加入。
 
确实是包含了 nfo文件，拖进去软件是没有反应的，一般也不会去处理nfo文件，如果把nfo文件也认作视频的话则是基本无法识别视频出来
![image](https://github.com/nuthx/subtitle-renamer/assets/51018113/bbcf3fb7-0ff4-4f23-80f2-e9b94b8cb790)

**Comment by nuthx** [comment]
bug已修复，增加了复制/剪切选择
https://github.com/nuthx/subtitle-renamer/releases/tag/1.6
