### ISSUE TITLE
排序的bug

### ISSUE THREAD

**Issue by hurriedlu** [nuthx/subtitle-renamer#14]
发现一个小bug，具体如图所示：
![image](https://github.com/nuthx/subtitle-renamer/assets/84308195/1758f84b-4a4d-4d8b-8b42-60da69fe68ca)
简单的说就是排序问题，09下面应该是10，但100先上了。另外有一个字幕导入的时候提示无法识别，不知道为什么。
![image](https://github.com/nuthx/subtitle-renamer/assets/84308195/72c89c4c-7de6-4414-b3ac-e69b0dcd6f0a)

**Comment by hurriedlu** [comment]
下面这是出现问题的字幕，里面一共有两个文件，51是正常的，52是有问题提示无法识别的。52字幕改名后也能被播放器自动识别并播放，不清楚是为什么。另：非常好的软件，使我的硬盘飞速旋转
[字幕.zip](https://github.com/nuthx/subtitle-renamer/files/14219723/default.zip)

**Comment by nuthx** [comment]
排序没有写规则，用sort()默认排的，只会在位数增加的时候出现乱序，情况比较少见，所以不打算做支持，分成两次拖入+重命名吧。

问题2可能是字幕内容不符合规则所以忽略了该字幕文件。因为简繁识别需要识别出字幕的每一句话，所以字幕不遵循ass/srt写法的话，就可能会出现识别失败跳过的情况。我年后看一下是字幕的问题还是程序识别的问题。

另祝新年快乐！

**Comment by hurriedlu** [comment]
> 排序没有写规则，用sort()默认排的，只会在位数增加的时候出现乱序，情况比较少见，所以不打算做支持，分成两次拖入+重命名吧。
> 
> 问题2可能是字幕内容不符合规则所以忽略了该字幕文件。因为简繁识别需要识别出字幕的每一句话，所以字幕不遵循ass/srt写法的话，就可能会出现识别失败跳过的情况。我年后看一下是字幕的问题还是程序识别的问题。
> 
> 另祝新年快乐！

sort居然有这种问题，涨知识了。不知道java c++里有没这个问题，过两天调试好服务器了研究一下。要是有机会看看比较方法是咋写的。
不修复也行，毕竟这么多集的番剧确实少见，手动多拖几次就能解决。要是解决的话我感觉得单独写一个比较方法（按照c++的套路）？可能默认的比较方法不适合比较string类型。没准后期也学下python然后自己填一下这个坑233333

另：祝你也新年快乐

**Comment by nuthx** [comment]
第52集字幕的371行，少了一个英文逗号，导致字幕识别失败

<img width="985" alt="ass" src="https://github.com/nuthx/subtitle-renamer/assets/29234438/e937a151-ead2-49f7-8f67-b8a12c99a483">

**Comment by zhongfly** [comment]
可以试试用别的排序库来做
例如 https://github.com/SethMMorton/natsort
```
>>> a = ['1','2','10','11','20','100']
>>> sorted(a)
['1', '10', '100', '11', '2', '20']
>>> natsort.natsorted(a)
['1', '2', '10', '11', '20', '100']
```

**Comment by dyphire** [comment]
python 自带的 sort 算法很一般，不只是数字排序有问题，它还无法正确处理非拉丁字符的排序。上面推荐的 [natsort](https://github.com/SethMMorton/natsort) 算法要强大的多，还支持调用各平台的原生排序算法，可以做到正确排序，建议更换排序算法

**Comment by nuthx** [comment]
1.7版本开始使用natsort排序

[Releasse](https://github.com/nuthx/subtitle-renamer/releases/tag/1.7)
