### ISSUE TITLE
Windows8.1启动报错ImportError: DLL load failed while importing QtWidgets: 找不到指定的程序

### ISSUE THREAD

**Issue by fnscar** [nuthx/subtitle-renamer#17]
![图片](https://github.com/nuthx/subtitle-renamer/assets/18730988/1b00e422-d3dc-4c6b-84a2-b8abae333c04)
迫切需要支持strm的重命名工具，大佬的项目支持手动添加视频格式就很棒。但是一打开就报错。。。

**Comment by fnscar** [comment]
还是一样的报错

**Comment by nuthx** [comment]
可能是pyqt的系统兼容性问题？
手上win10和win11都测过了，暂时没找到win8.1的电脑

条件允许的话，尝试本地编译运行一下，看能否定位出问题
