### ISSUE TITLE
部分SSA字幕无法识别

### ISSUE THREAD

**Issue by morisama11** [nuthx/subtitle-renamer#18]
拖入ssa字幕时，显示无法识别字幕
![PixPin_2024-04-08_16-39-59](https://github.com/nuthx/subtitle-renamer/assets/101331616/9d4faa07-762f-447c-af53-892c1beedfe5)

**Comment by nuthx** [comment]
应该是字幕文件的格式不标准，没有被读取出来
可以在设置中关闭简繁识别再尝试一次

如果方便， 能否提供一下字幕文件，我排查一下错误原因
