### ISSUE TITLE
设置页面无法完全显示

### ISSUE THREAD

**Issue by wzdc** [nuthx/subtitle-renamer#23]
有一小部分被任务栏遮挡
![image](https://github.com/nuthx/subtitle-renamer/assets/53571020/61e4912e-da7b-430e-a14d-06cb0533c564)

**Comment by nuthx** [comment]
没考虑到小屏幕的情况，下版本中改成滑动页面

**Comment by zengjiu** [comment]
一样的bug  无法保存
