### ISSUE TITLE
手动指定字幕繁简

### ISSUE THREAD

**Issue by Lazy-Beee** [nuthx/subtitle-renamer#9]
**问题描述**
对于普通的单集字幕，繁简识别准确率非常高。然而对于某些日语占比较高的字幕，繁简识别就不是很稳定。

**期望改进**
能不能添加一个手动改变繁简识别结果的功能？

**截图**
一些OP/ED的歌词，全部为简体
![image](https://github.com/nuthx/subtitle-renamer/assets/85976834/78aeabf5-b493-42d5-acb7-03d0eff64929)

**字幕文件**
[ass.zip](https://github.com/nuthx/subtitle-renamer/files/12570005/ass.zip)

**Comment by nuthx** [comment]
1.4版本已加入手动更正语言功能
